# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0
name: Pull Request Workflow
on: # yamllint disable-line rule:truthy
  pull_request:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pr-checks:
    uses: diggsweden/reusable-ci/.github/workflows/pullrequest-orchestrator.yml@12603231353981dadbe2c56a056e611528f29a15 # v2.4.3
    permissions:
      contents: read
      packages: read
      security-events: write
    secrets: inherit
    with:
      project-type: maven
      linters.justmiselint: true
      linters.commitlint: false
      linters.licenselint: false
      linters.megalint: false
      linters.publiccodelint: false
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
      - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3
        with:
          just-version: 1.43.0
      - name: Run tests
        run: just test
