# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0
name: Test Unit Fedora
on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - 'libs/**'
      - 'tests/**'
      - 'setup.sh'
      - 'dot/.config/devbase/packages.yaml'
      - '.github/workflows/test-unit-fedora.yml'
  push:
    branches:
      - main
    paths:
      - 'libs/**'
      - 'tests/**'
      - 'setup.sh'
      - 'dot/.config/devbase/packages.yaml'
      - '.github/workflows/test-unit-fedora.yml'
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:43
    steps:
      - name: Install prerequisites
        run: |
          dnf install -y git just
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
      - name: Setup test dependencies
        run: just test-setup
      - name: Run tests
        run: just test
