# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0
name: Test Unit Ubuntu
on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - 'libs/**'
      - 'tests/**'
      - 'setup.sh'
      - 'dot/.config/devbase/packages.yaml'
      - '.github/workflows/test-unit-ubuntu.yml'
  push:
    branches:
      - main
    paths:
      - 'libs/**'
      - 'tests/**'
      - 'setup.sh'
      - 'dot/.config/devbase/packages.yaml'
      - '.github/workflows/test-unit-ubuntu.yml'
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install CI dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pipx fish jq
          pipx ensurepath
      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
      - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3
        with:
          just-version: 1.43.0
      - name: Setup test dependencies
        run: just test-setup
      - name: Run tests
        run: just test
